### ISSUE TITLE
`initialize_sciencebase_session()` functions on install from github but not CRAN for release 1.3.0

### ISSUE THREAD

**Issue by sformel-usgs** [DOI-USGS/sbtools#318]
We chatted about this a bit in the MS Teams channel.  On 2023-12-21 I tested sbtools:
```
install.packages("sbtools")
library("sbtools")
initialize_sciencebase_session()
```
After pasting in the token, it returned:

> A browser will open https://sciencebase.usgs.gov/manager/
>   Log in and copy a token from the 'User' menu in the upper right.
> Paste the token in the dialogue box that opens.
> Error in file(file, ifelse(append, "a", "w")) :
>   cannot open the connection
> In addition: Warning message:
>   In file(file, ifelse(append, "a", "w")) :
>   cannot open file 'C:\Users\CRAN\AppData\Roaming/R/data/R/sbtools/token': No such file or directory

I then installed the github version from this repo:
`remotes::install_github("DOI-USGS/sbtools")`
which triggered the following updates:

> yaml     (2.3.7 -> 2.3.8)
> sodium   (1.2.1 -> 1.3.1)
> openssl  (2.1.0 -> 2.1.1)
> filelock (1.0.2 -> 1.0.3)
> jsonlite (1.8.7 -> 1.8.8)
> keyring  (1.3.1 -> 1.3.2)
> cli      (3.6.1 -> 3.6.2)

After the github installation, `initialize_sciencebase_session()` worked without a problem. However, I tested it once more, first removing `sbtools` and then installing from CRAN, followed by installation from this repo.  The CRAN installation returned the same error, so the updates aren't likely to be the culprit.  Installing from github now results in something else, which may be a connection problem, not a package problem:

> Request failed [400]. Retrying in 1 seconds...
> Request failed [400]. Retrying in 2.4 seconds...
> A browser will open https://sciencebase.usgs.gov/manager/
>   Log in and copy a token from the 'User' menu in the upper right.
> Paste the token in the dialogue box that opens.
> [1] TRUE
> Warning message:
>   In token_refresh() :
>   Unable to refresh SB cloud token. Some functionality may not work.

I tried again and it returned `TRUE` with no need to copy and paste token.

<details>
<summary>sessionInfo()</summary>

> R version 4.3.1 (2023-06-16 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19045)
> 
> Matrix products: default
> 
> 
> locale:
> [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.utf8    
> 
> time zone: America/Chicago
> tzcode source: internal
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] sbtools_1.3.0
> 
> loaded via a namespace (and not attached):
>  [1] utf8_1.2.3        R6_2.5.1          tidyselect_1.2.0  magrittr_2.0.3    remotes_2.4.2.1   glue_1.6.2        tibble_3.2.1      pkgconfig_2.0.3   dplyr_1.1.3      
> [10] generics_0.1.3    lifecycle_1.0.3   cli_3.6.2         fansi_1.0.4       vctrs_0.6.3       compiler_4.3.1    httr_1.4.7        rstudioapi_0.15.0 tools_4.3.1      
> [19] curl_5.2.0        mime_0.12         pillar_1.9.0      jsonlite_1.8.8    rlang_1.1.1    
  
</details>

**Comment by dblodgett-usgs** [comment]
@sformel-usgs -- I think I have this fixed. Since it's realted to the CRAN build, I'm not sure we can test it until the next release, but the open PR from the token branch has what I think is a fix for the token cache path issue.

**Comment by sformel-usgs** [comment]
Sounds good, feel free to ping me when the release happens and I'll test it out.

**Comment by msleckman** [comment]
``` 
> library(sbtools)
> initialize_sciencebase_session()
Please enter your username:msleckman@usgs.gov
Request failed [400]. Retrying in 1.4 seconds...
Request failed [400]. Retrying in 1 seconds...
A browser will open https://sciencebase.usgs.gov/manager/
Log in and copy a token from the 'User' menu in the upper right.
Paste the token in the dialogue box that opens.
[1] TRUE
Warning message:
In token_refresh() :
  Unable to refresh SB cloud token. Some functionality may not work.
> initialize_sciencebase_session()
Please enter your username:username@usgs.gov
[1] TRUE
```

Looks like it works for me now. 👍 🎉
