### ISSUE TITLE
Temp `Request failed [400]` message after `sbtools::initialize_sciencebase_session()` (non-blocker)

### ISSUE THREAD

**Issue by msleckman** [DOI-USGS/sbtools#319]
In R, after initializing the sb session and entering my username to open a new browser window to the sciencebase bisonconnect webpage, I get 1 or 2 messages of failed api request as shown in the code snippet below. After those messages pass, the initialization seems successful, and the sciencebase browser window ultimately opens and the popup for the token appears. 

While it doesn't seem like it preventing me from authenticating sb, I am wondering why I am getting the failed request error.

``` 
> sbtools::initialize_sciencebase_session()
Please enter your username:username@usgs.gov
Request failed [400]. Retrying in 1 seconds...
Request failed [400]. Retrying in 1.4 seconds...
A browser will open https://sciencebase.usgs.gov/manager/
Log in and copy a token from the 'User' menu in the upper right.
Paste the token in the dialogue box that opens.
```

**Comment by dblodgett-usgs** [comment]
Yeah -- that's not actually a problem. It just means that your old token didn't work. There's an `httr::RETRY` call that is set to the default verbosity. I'll set it to quiet.

**Comment by dblodgett-usgs** [comment]
@msleckman can you try out the version I have on the token branch and see if it's better?

`remotes::install_github("doi-usgs/sbtools@token")`

**Comment by msleckman** [comment]
I remove.package('sbtools') then installed the line you pasted above. 
```
> library(sbtools)
> user <- Sys.getenv("msleckman") # this should be your science base user id
> sbtools::initialize_sciencebase_session()
Please enter your username:msleckman@usgs.gov
Request failed [400]. Retrying in 1.6 seconds...
Request failed [400]. Retrying in 1.8 seconds...
A browser will open https://sciencebase.usgs.gov/manager/
Log in and copy a token from the 'User' menu in the upper right.
Paste the token in the dialogue box that opens.
```
Still get request failed message.

**Comment by msleckman** [comment]
Actually it worked! I hadn't restarted my R session.
