### ISSUE TITLE
confusing warning when logging in with role accounts

### ISSUE THREAD

**Issue by jesse-ross** [DOI-USGS/sbtools#323]
Role accounts still log in with password authentication, so we have to use `authenticate_sb()`. When doing this, we get a confusing error message which makes it seem as though login has failed. But login has succeeded!

```
> sbtools::authenticate_sb(username = cidamanager$username, password = cidamanager$password)
authenticate_sb will stop working in favor of initialize_sciencebase_session when sciencebase turns off username and password login
Warning message:
In sbtools::authenticate_sb(username = cidamanager$username, password = cidamanager$password) :
  Unable to authenticate to legacy SB.
> sbtools::is_logged_in()
[1] TRUE
```

Happy to throw together a quick PR to improve this a bit if you like, just let me know!

**Comment by dblodgett-usgs** [comment]
I've seen this as well and meant to try and fix it. If you can put in a PR, to address it, I'd appreciate it!
